# Load the Python Standard and DesignScript Libraries
import sys
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# The inputs to this node will be stored as a list in the IN variables.
listOfService = IN[0]
listOfElementsCategory = IN[1]

# Custom variables
listLoop = 0

DRYWALL_SIMPLES = {"DRYWALL_SIMPLES": [], "title": []}
DRYWALL_DUPLA = {"DRYWALL_DUPLA": [], "title": []}
CHAPISCO_EXT_SERV = {"CHAPISCO_EXT_SERV": [], "title": []}
EMBOCO_EXT_SERV_25mm = {"EMBOCO_EXT_SERV_25mm": [], "title": []}
EMBOCO_EXT_SERV_35mm = {"EMBOCO_EXT_SERV_35mm": [], "title": []}
EMBOCO_EXT_SERV_45mm = {"EMBOCO_EXT_SERV_45mm": [], "title": []}
EMBOCO_EXT_SERV_50mm = {"EMBOCO_EXT_SERV_50mm": [], "title": []}
MASSA_UNICA_EXT_SERV_25mm = {"MASSA_UNICA_EXT_SERV_25mm": [], "title": []}
MASSA_UNICA_EXT_SERV_35mm = {"MASSA_UNICA_EXT_SERV_35mm": [], "title": []}
MASSA_UNICA_EXT_SERV_45mm = {"MASSA_UNICA_EXT_SERV_45mm": [], "title": []}
MASSA_UNICA_EXT_SERV_50mm = {"MASSA_UNICA_EXT_SERV_50mm": [], "title": []}
CERAMICA_PORCELANA_EXT_5X5cm = {"CERAMICA_PORCELANA_EXT_5X5cm": [], "title": []}
CERAMICA_PORCELANA_EXT_5X10cm = {"CERAMICA_PORCELANA_EXT_5X10cm": [], "title": []}
MASSA_CORRIDA_ACRILICA_EXT_UMA_DEMAO_MULTPAV_SERV = {"MASSA_CORRIDA_ACRILICA_EXT_UMA_DEMAO_MULTPAV_SERV": [], "title": []}
MASSA_CORRIDA_ACRILICA_EXT_DUAS_DEMAOS_MULTPAV_SERV = {"MASSA_CORRIDA_ACRILICA_EXT_DUAS_DEMAOS_MULTPAV_SERV": [], "title": []}
SELADOR_ACRILICO_EXT_MULTPAV_SERV = {"SELADOR_ACRILICO_EXT_MULTPAV_SERV": [], "title": []}
PINTURA_ACRILICA_EXT_MULTPAV_SERV = {"PINTURA_ACRILICA_EXT_MULTPAV_SERV": [], "title": []}
TEXTURA_ACRILICA_EXT_UMA_COR_MULTPAV_SERV = {"TEXTURA_ACRILICA_EXT_UMA_COR_MULTPAV_SERV": [], "title": []}
TEXTURA_ACRILICA_EXT_DUAS_CORES_MULTPAV_SERV = {"TEXTURA_ACRILICA_EXT_DUAS_CORES_MULTPAV_SERV": [], "title": []}

# Place your code below this line
for i in listOfService:
	for j in i:
		if j == "DRYWALL_SIMPLES":
			DRYWALL_SIMPLES[j].append(listOfElementsCategory[listLoop])
			DRYWALL_SIMPLES["title"].insert(0, "DRYWALL_SIMPLES")
		elif j == "DRYWALL_DUPLA":
			DRYWALL_DUPLA[j].append(listOfElementsCategory[listLoop])
			DRYWALL_DUPLA["title"].insert(0, "DRYWALL_DUPLA")
		elif j == "CHAPISCO_EXT_SERV":
			CHAPISCO_EXT_SERV[j].append(listOfElementsCategory[listLoop])
			CHAPISCO_EXT_SERV["title"].insert(0, "CHAPISCO_EXT_SERV")
		elif j == "EMBOCO_EXT_SERV_25mm":
			EMBOCO_EXT_SERV_25mm[j].append(listOfElementsCategory[listLoop])
			EMBOCO_EXT_SERV_25mm["title"].insert(0, "EMBOCO_EXT_SERV_25mm")
		elif j == "EMBOCO_EXT_SERV_35mm":
			EMBOCO_EXT_SERV_35mm[j].append(listOfElementsCategory[listLoop])
			EMBOCO_EXT_SERV_35mm["title"].insert(0, "EMBOCO_EXT_SERV_35mm")
		elif j == "EMBOCO_EXT_SERV_45mm":
			EMBOCO_EXT_SERV_45mm[j].append(listOfElementsCategory[listLoop])
			EMBOCO_EXT_SERV_45mm["title"].insert(0, "EMBOCO_EXT_SERV_45mm")
		elif j == "EMBOCO_EXT_SERV_50mm":
			EMBOCO_EXT_SERV_50mm[j].append(listOfElementsCategory[listLoop])
			EMBOCO_EXT_SERV_50mm["title"].insert(0, "EMBOCO_EXT_SERV_50mm")
		elif j == "MASSA_UNICA_EXT_SERV_25mm":
			MASSA_UNICA_EXT_SERV_25mm[j].append(listOfElementsCategory[listLoop])
			MASSA_UNICA_EXT_SERV_25mm["title"].insert(0, "MASSA_UNICA_EXT_SERV_25mm")	
		elif j == "MASSA_UNICA_EXT_SERV_35mm":
			MASSA_UNICA_EXT_SERV_35mm[j].append(listOfElementsCategory[listLoop])
			MASSA_UNICA_EXT_SERV_35mm["title"].insert(0, "MASSA_UNICA_EXT_SERV_35mm")	
		elif j == "MASSA_UNICA_EXT_SERV_45mm":
			MASSA_UNICA_EXT_SERV_45mm[j].append(listOfElementsCategory[listLoop])
			MASSA_UNICA_EXT_SERV_45mm["title"].insert(0, "MASSA_UNICA_EXT_SERV_45mm")	
		elif j == "MASSA_UNICA_EXT_SERV_50mm":
			MASSA_UNICA_EXT_SERV_50mm[j].append(listOfElementsCategory[listLoop])
			MASSA_UNICA_EXT_SERV_50mm["title"].insert(0, "MASSA_UNICA_EXT_SERV_50mm")	
		elif j == "CERAMICA_PORCELANA_EXT_5X5cm":
			CERAMICA_PORCELANA_EXT_5X5cm[j].append(listOfElementsCategory[listLoop])
			CERAMICA_PORCELANA_EXT_5X5cm["title"].insert(0, "CERAMICA_PORCELANA_EXT_5X5cm")	
		elif j == "CERAMICA_PORCELANA_EXT_5X10cm":
			CERAMICA_PORCELANA_EXT_5X10cm[j].append(listOfElementsCategory[listLoop])
			CERAMICA_PORCELANA_EXT_5X10cm["title"].insert(0, "CERAMICA_PORCELANA_EXT_5X10cm")	
		elif j == "MASSA_CORRIDA_ACRILICA_EXT_UMA_DEMAO_MULTPAV_SERV":
			MASSA_CORRIDA_ACRILICA_EXT_UMA_DEMAO_MULTPAV_SERV[j].append(listOfElementsCategory[listLoop])
			MASSA_CORRIDA_ACRILICA_EXT_UMA_DEMAO_MULTPAV_SERV["title"].insert(0, "MASSA_CORRIDA_ACRILICA_EXT_UMA_DEMAO_MULTPAV_SERV")	
		elif j == "MASSA_CORRIDA_ACRILICA_EXT_DUAS_DEMAOS_MULTPAV_SERV":
			MASSA_CORRIDA_ACRILICA_EXT_DUAS_DEMAOS_MULTPAV_SERV[j].append(listOfElementsCategory[listLoop])
			MASSA_CORRIDA_ACRILICA_EXT_DUAS_DEMAOS_MULTPAV_SERV["title"].insert(0, "MASSA_CORRIDA_ACRILICA_EXT_DUAS_DEMAOS_MULTPAV_SERV")
		elif j == "SELADOR_ACRILICO_EXT_MULTPAV_SERV":
			SELADOR_ACRILICO_EXT_MULTPAV_SERV[j].append(listOfElementsCategory[listLoop])
			SELADOR_ACRILICO_EXT_MULTPAV_SERV["title"].insert(0, "SELADOR_ACRILICO_EXT_MULTPAV_SERV")
		elif j == "PINTURA_ACRILICA_EXT_MULTPAV_SERV":
			PINTURA_ACRILICA_EXT_MULTPAV_SERV[j].append(listOfElementsCategory[listLoop])
			PINTURA_ACRILICA_EXT_MULTPAV_SERV["title"].insert(0, "PINTURA_ACRILICA_EXT_MULTPAV_SERV")
		elif j == "TEXTURA_ACRILICA_EXT_UMA_COR_MULTPAV_SERV":
			TEXTURA_ACRILICA_EXT_UMA_COR_MULTPAV_SERV[j].append(listOfElementsCategory[listLoop])
			TEXTURA_ACRILICA_EXT_UMA_COR_MULTPAV_SERV["title"].insert(0, "TEXTURA_ACRILICA_EXT_UMA_COR_MULTPAV_SERV")
		elif j == "TEXTURA_ACRILICA_EXT_DUAS_CORES_MULTPAV_SERV":
			TEXTURA_ACRILICA_EXT_DUAS_CORES_MULTPAV_SERV[j].append(listOfElementsCategory[listLoop])
			TEXTURA_ACRILICA_EXT_DUAS_CORES_MULTPAV_SERV["title"].insert(0, "TEXTURA_ACRILICA_EXT_DUAS_CORES_MULTPAV_SERV")

	listLoop = listLoop + 1

# Assign your output to the OUT variable.
OUT = DRYWALL_SIMPLES["title"] + DRYWALL_DUPLA["title"] + CHAPISCO_EXT_SERV["title"] + EMBOCO_EXT_SERV_25mm["title"] + EMBOCO_EXT_SERV_35mm["title"] + EMBOCO_EXT_SERV_45mm["title"] + EMBOCO_EXT_SERV_50mm["title"] + MASSA_UNICA_EXT_SERV_25mm["title"] + MASSA_UNICA_EXT_SERV_35mm["title"] + MASSA_UNICA_EXT_SERV_45mm["title"] + MASSA_UNICA_EXT_SERV_50mm["title"] + CERAMICA_PORCELANA_EXT_5X5cm["title"] + CERAMICA_PORCELANA_EXT_5X10cm["title"] + MASSA_CORRIDA_ACRILICA_EXT_UMA_DEMAO_MULTPAV_SERV["title"] + MASSA_CORRIDA_ACRILICA_EXT_DUAS_DEMAOS_MULTPAV_SERV["title"] + SELADOR_ACRILICO_EXT_MULTPAV_SERV["title"] + PINTURA_ACRILICA_EXT_MULTPAV_SERV["title"] + TEXTURA_ACRILICA_EXT_UMA_COR_MULTPAV_SERV["title"] + TEXTURA_ACRILICA_EXT_DUAS_CORES_MULTPAV_SERV["title"], DRYWALL_SIMPLES["DRYWALL_SIMPLES"], DRYWALL_DUPLA["DRYWALL_DUPLA"], CHAPISCO_EXT_SERV["CHAPISCO_EXT_SERV"], EMBOCO_EXT_SERV_25mm["EMBOCO_EXT_SERV_25mm"], EMBOCO_EXT_SERV_35mm["EMBOCO_EXT_SERV_35mm"], EMBOCO_EXT_SERV_45mm["EMBOCO_EXT_SERV_45mm"], EMBOCO_EXT_SERV_50mm["EMBOCO_EXT_SERV_50mm"], MASSA_UNICA_EXT_SERV_25mm["MASSA_UNICA_EXT_SERV_25mm"], MASSA_UNICA_EXT_SERV_35mm["MASSA_UNICA_EXT_SERV_35mm"], MASSA_UNICA_EXT_SERV_45mm["MASSA_UNICA_EXT_SERV_45mm"], MASSA_UNICA_EXT_SERV_50mm["MASSA_UNICA_EXT_SERV_50mm"], CERAMICA_PORCELANA_EXT_5X5cm["CERAMICA_PORCELANA_EXT_5X5cm"], CERAMICA_PORCELANA_EXT_5X10cm["CERAMICA_PORCELANA_EXT_5X10cm"], MASSA_CORRIDA_ACRILICA_EXT_UMA_DEMAO_MULTPAV_SERV["MASSA_CORRIDA_ACRILICA_EXT_UMA_DEMAO_MULTPAV_SERV"], MASSA_CORRIDA_ACRILICA_EXT_DUAS_DEMAOS_MULTPAV_SERV["MASSA_CORRIDA_ACRILICA_EXT_DUAS_DEMAOS_MULTPAV_SERV"], SELADOR_ACRILICO_EXT_MULTPAV_SERV["SELADOR_ACRILICO_EXT_MULTPAV_SERV"], PINTURA_ACRILICA_EXT_MULTPAV_SERV["PINTURA_ACRILICA_EXT_MULTPAV_SERV"], TEXTURA_ACRILICA_EXT_UMA_COR_MULTPAV_SERV["TEXTURA_ACRILICA_EXT_UMA_COR_MULTPAV_SERV"], TEXTURA_ACRILICA_EXT_DUAS_CORES_MULTPAV_SERV["TEXTURA_ACRILICA_EXT_DUAS_CORES_MULTPAV_SERV"]